fix: only set Utility property if namespace empty
If the Utility namespace has concrete values and the const Utility
property is set it causes `error TS2300: Duplicate identifier 'Utility'.`
This tracks whether any values are added to the Utility namespace and
only sets the property workaround if there are none.